DeepSwarm:
    save_folder:
    metrics: accuracy
    max_depth: 2
    reuse_patience: 1

    aco:
        pheromone:
            start: 0.1
            decay: 0.1
            evaporation: 0.1
        greediness: 0.5
        ant_count: 2

    backend:
        epochs: 1
        batch_size: 64
        patience: 1
        loss: categorical_crossentropy

Nodes:
    InputNode:
        attributes: 
            shape: [!!python/tuple [32, 32, 3]]
        transitions:
            Conv2DNode: 1.0
        repetition_penalty: 1

    Conv2DNode:
        attributes:
            filter_number: [16, 32, 64]
            kernel_size: [1, 3, 5]
            activation: [ELU, ReLU, LeakyReLU]
        transitions:
            Conv2DNode: 1.0
            Pool2DNode: 1.2
            FlattenNode: 0.8
            BatchNormalizationNode: 1
        repetition_penalty: 0.5

    BatchNormalizationNode:
        attributes: {}
        transitions:
            Conv2DNode: 1.1
            Pool2DNode: 1.0
            FlattenNode: 1.0
        repetition_penalty: 0.5

    Pool2DNode:
        attributes:
            type: [max, average]
            pool_size: [2]
            stride: [2, 3]
        transitions:
            Conv2DNode: 1.1
            FlattenNode: 1.0
            BatchNormalizationNode: 1.0
        repetition_penalty: 0.5

    FlattenNode:
        attributes: {}
        transitions:
            DenseNode: 1.0
        repetition_penalty: 0.5

    DenseNode:
        attributes:
            output_size: [32, 64, 128, 256]
            activation: [ELU, ReLU, LeakyReLU, Sigmoid]
        transitions:
            DenseNode: 1.0
            DropoutNode: 1.2
        repetition_penalty: 0.5

    DropoutNode:
        attributes:
            rate: [0.1, 0.3, 0.5]
        transitions:
            DenseNode: 1.0
        repetition_penalty: 0.5

    EndNode:
        attributes:
            output_size: [10]
            activation: [Softmax]
        transitions: {}
        repetition_penalty: 1
