DeepSwarm:
    save_folder:
    metrics: accuracy
    max_depth: 15
    reuse_patience: 1

    aco:
        pheromone:
            start: 0.1
            decay: 0.1
            evaporation: 0.1
        greediness: 0.5
        ant_count: 15

    backend:
        epochs: 15
        batch_size: 64
        patience: 5
        loss: sparse_categorical_crossentropy

Nodes:
    InputNode:
        attributes: 
            shape: [!!python/tuple [28, 28, 1]]
        transitions:
            Conv2DNode: 1.0

    Conv2DNode:
        attributes:
            filter_number: [16, 32, 64]
            kernel_size: [1, 3, 5]
            activation: [ReLU]
        transitions:
            Conv2DNode: 0.8
            Pool2DNode: 1.2
            FlattenNode: 1.0
            BatchNormalizationNode: 1.2

    BatchNormalizationNode:
        attributes: {}
        transitions:
            Conv2DNode: 1.1
            Pool2DNode: 1.1
            FlattenNode: 1.0

    Pool2DNode:
        attributes:
            type: [max, average]
            pool_size: [2]
            stride: [2, 3]
        transitions:
            Conv2DNode: 1.1
            FlattenNode: 1.0
            BatchNormalizationNode: 1.1

    FlattenNode:
        attributes: {}
        transitions:
            DenseNode: 1.0
            EndNode: 0.8

    DenseNode:
        attributes:
            output_size: [32, 64, 128, 256]
            activation: [ReLU, Sigmoid]
        transitions:
            DenseNode: 0.8
            DropoutNode: 1.2
            EndNode: 1.0

    DropoutNode:
        attributes:
            rate: [0.1, 0.3, 0.5]
        transitions:
            DenseNode: 1.0
            EndNode: 0.9

    EndNode:
        attributes:
            output_size: [10]
            activation: [Softmax]
        transitions: {}
